language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.0.0

script:
  - dotnet restore
  - dotnet build src/Gbfs.Net --configuration Release
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet pack src/Gbfs.Net --configuration Release /p:Version=$TRAVIS_TAG;
  dotnet nuget push src/Gbfs.Net/bin/Release/*.nupkg -k $NUGET_API_KEY;
  fi"