language: csharp

os: linux # Ubuntu 14.04
dist: trusty
group: edge
sudo: required
dotnet: 1.0.0-preview2-003121

services:
  - docker

script:
  - ./build.sh

deploy:
  provider: script
  script:
    - ./build.sh -t Publish
  on:
    all_branches: true